### ISSUE TITLE
Browser migration

### ISSUE THREAD

**Issue by abose** [phcode-dev/phoenix#11]
Browser does not have nodejs env. We have to create remove node dep from brackets to port to the browser while maintaining the feature compatibility.

### Remove deprecated npm flows
- [x] ~~https://github.com/aicore/phoenix/issues/9~~

### Remove all node based default extensions.
- [x] ~~brackets-eslint removed as part of this[ change](https://github.com/aicore/phoenix/issues/11)~~
- [x] ~~php tooling removed. Will not merge in phoenix core till we have dev request. https://github.com/aicore/phoenix/issues/8~~
- [x] ~~https://github.com/aicore/phoenix/issues/7~~
- [x] ~~https://github.com/aicore/phoenix/issues/13~~
- [x] ~~https://github.com/aicore/phoenix/issues/14~~
- [x] ~~https://github.com/aicore/phoenix/issues/15~~
- [x] ~~https://github.com/aicore/phoenix/issues/16~~

### Direct integration for their party deps instead of old NPM

- [x] ~~#40~~

### Build Nodejs compatibility layer in browser
- [x] ~~https://github.com/aicore/phoenix/issues/19~~
- [x] ~~https://github.com/aicore/phoenix/issues/3~~
- [x] ~~https://github.com/aicore/phoenix/issues/18~~

### Migrate functionality
- [x] ~~#22~~
- [x] ~~#24~~
- [x] ~~#26~~
- [x] #56
- [x] #58
- [x] ~~#27~~
- [x] #29
- [x] https://github.com/aicore/phoenix/issues/10

### Reinstate functionality
- [x] ~~#51~~
- [x] ~~#52~~
- [x] #209 - replaced with JSHint, marking as done as linter support is enaled. ESLint will be enabled only in installed builds.
- [x] #39
- [x] #38
- [x] ~~#47~~
- [x] #67
- [x] ~~#74~~

**Comment by abose** [comment]
Browser migration is complete. Closing.
