### ISSUE TITLE
Web Release checklist

### ISSUE THREAD

**Issue by abose** [phcode-dev/phoenix#829]
Before every web release, follow the below steps:
- [ ]  Full test suite run status
- [ ] the time to load average of 5 runs in staging.phcode.dev
- [ ] Offline test- Phoenix works offline after the first load. - time to load average of 5 runs.

**Comment by abose** [comment]
This is now mostly automated in pipelines. closing.
